wip

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -2,6 +2,36 @@
 
 set -euo pipefail
 
+# what tags are we talking about?
+old_tag="$(svu current)"
+new_tag="$(svu minor)"
+
+main() {
+  # sanity
+  [ -n "${GITHUB_TOKEN:-}" ] || fatal "GITHUB_TOKEN is required"
+  [ -z "$(git status --porcelain)" ] || fatal "git worktree is dirty"
+  [ -z "$(git tag -l "${new_tag}")" ] || fatal "tag already exists: ${new_tag}"
+
+  # confirm
+  banner "are you sure?"
+  echo
+  gum confirm "Tag ${old_tag} => ${new_tag} and release?"
+
+  # tag
+  banner "creating tag ${new_tag}..."
+  git tag "${new_tag}"
+  git push origin "${new_tag}"
+
+  # goreleaseer
+  banner "goreleaser..."
+  goreleaser healthcheck
+  goreleaser release --clean
+}
+
+#
+# helpers
+#
+
 banner() {
   printf '\e[1;38;5;231;48;2;64;160;43m[%s] %-72s\e[0m\n' "$(date '+%H:%M:%S')" "$1"
 }
@@ -10,33 +40,5 @@ fatal() {
   exit 1
 }
 
-# what tags are we talking about?
-old_tag="$(svu current)"
-if [[ "${1:-}" == "--rc" ]]; then
-  new_tag="$(svu minor --prerelease rc)"
-else
-  new_tag="$(svu minor)"
-fi
-
-# sanity
-[ -n "${GITHUB_TOKEN:-}" ] || fatal "GITHUB_TOKEN is required"
-[ -z "$(git status --porcelain)" ] || fatal "git worktree is dirty"
-[ -z "$(git tag -l "${new_tag}")" ] || fatal "tag already exists: ${new_tag}"
-
-# confirm
-banner "are you sure?"
-echo
-gum confirm "Release ${old_tag} => ${new_tag}?"
-
-# tag
-banner "creating tag ${new_tag}..."
-git tag "${new_tag}"
-git push origin "${new_tag}"
-
-# goreleaseer
-banner "goreleaser..."
-goreleaser healthcheck
-goreleaser release --clean
-
-# done
-banner "✓ release ✓"
+# go
+main
